version: '3.4'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_USER=yuri
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=financeiro
      - MYSQL_PORT=3306
    hostname: database
    healthcheck:
      test: ['CMD-SHELL']

  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    hostname: financeiro
    healthcheck:
      test: [ 'CMD-SHELL' ]
